FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY server/DocumentsKMTest/DocumentsKMTest.csproj server/DocumentsKMTest/
COPY . .
WORKDIR /src/server/DocumentsKMTest/
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "test", "DocumentsKMTest.csproj"]