FROM nginx:alpine

# Copy built static files to nginx container
COPY ./public /usr/share/nginx.html

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy a new config
COPY nginx/nginx.conf /etc/nginx/conf.d

# Expose Nginx default port
EXPOSE 80

# Start the server
ENTRYPOINT ["nginx", "-g", "daemon off;"]