version: '3.8'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:80"
        volumes:
            - type: bind
              source: ./public/
              target: /usr/share/nginx/html/
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    rabbitmq:
        image: rabbitmq:3-management-alpine
        volumes:
            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672