version: '3.8'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:80"
        volumes:
            - type: bind
              source: ./public/
              target: /usr/share/nginx/html/